homebrew_cask_packages:
  - alt-tab
  - bettertouchtool
  - docker-desktop
  - font-fira-code-nerd-font
  - hammerspoon
  - itsycal
  - little-snitch
  - rectangle
  - wezterm

homebrew_packages:
  - atuin
  - cmake
  - direnv
  - entr
  - eza 
  - fzf
  - gh
  - git
  - git-delta
  - golang
  - gpg
  - htop
  - hyperfine
  - imagemagick
  - jq
  - just
  - neovim
  - nmap
  - nodejs
  - ripgrep
  - rsync
  - tig
  - tmux
  - wget
  - zoxide
  - zsh
